/**
 * 由 src/kubernetes/gen/index.ts 自动生成
 * !!! 请不要修改 !!!
 */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * License is the Schema for the Licenses API
 */
export interface License {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   */
  apiVersion?: string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   */
  kind?: string;
  metadata?: {
    [k: string]: any;
  };
  /**
   * LicenseSpec defines the desired state of License
   */
  spec?: {
    /**
     * Applied license ids
     */
    licenseIDs?: string[];
    /**
     * PlatformID is the id of the current platform.
     */
    platformID?: string;
    [k: string]: any;
  };
  /**
   * LicenseStatus defines the observed state of License
   */
  status?: {
    /**
     * The encrypted license content
     */
    encrypted?: string;
    /**
     * The error message for license IDs parsing
     */
    errMessage?: string;
    /**
     * Parsed license ids
     */
    licenseIDs?: string[];
    /**
     * The plainText license content
     */
    plainText?: {
      durationDays?: number;
      endTime?: string;
      limits?: {
        [k: string]: number;
      };
      modulebits?: string;
      product?: string;
      startTime?: string;
      [k: string]: any;
    }[];
    [k: string]: any;
  };
  [k: string]: any;
}
