/**
 * 由 src/kubernetes/gen/index.ts 自动生成
 * !!! 请不要修改 !!!
 */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ResourceAggregationView is a specification for a ResourceAggregationView resource
 */
export interface ResourceAggregationView {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   */
  apiVersion?: string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   */
  kind?: string;
  metadata?: {
    [k: string]: any;
  };
  /**
   * ResourceAggregationViewSpec defines the desired state of ResourceAggregationView
   */
  spec?: {
    columns?: {
      exportLabels?: boolean;
      isPrimary?: boolean;
      name: string;
      resourceRef?: {
        field: string;
        [k: string]: any;
      };
      type?: string;
      [k: string]: any;
    }[];
    filters?: {
      field: string;
      operator: string;
      [k: string]: any;
    }[];
    resourceTypes?: {
      group: string;
      kind: string;
      version: string;
      [k: string]: any;
    }[];
    [k: string]: any;
  };
  /**
   * ResourceAggregationViewStatus defines the observed state of ResourceAggregationView
   */
  status?: {
    observedGeneration?: number;
    status: string;
    [k: string]: any;
  };
  [k: string]: any;
}
