/**
 * 由 src/kubernetes/gen/index.ts 自动生成
 * !!! 请不要修改 !!!
 */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Tenant is the Schema for the tenants API.
 */
export interface Tenant {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   */
  apiVersion?: string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   */
  kind?: string;
  metadata?: {
    [k: string]: any;
  };
  /**
   * TenantSpec defines the desired state of Tenant.
   */
  spec?: {
    /**
     * AdditionalResources specifies additional resources that will be created with the tenant
     */
    additionalResources?: {
      /**
       * list of k8s resources in yaml format
       */
      items: string[];
      /**
       * A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
       */
      namespaceSelector?: {
        /**
         * matchExpressions is a list of label selector requirements. The requirements are ANDed.
         */
        matchExpressions?: {
          /**
           * key is the label key that the selector applies to.
           */
          key: string;
          /**
           * operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
           */
          operator: string;
          /**
           * values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
           */
          values?: string[];
          [k: string]: any;
        }[];
        /**
         * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
         */
        matchLabels?: {
          [k: string]: string;
        };
        [k: string]: any;
      };
      [k: string]: any;
    };
    /**
     * Specifies additional RoleBindings assigned to the Tenant. Capsule will ensure that all namespaces in the Tenant always contain the RoleBinding for the given ClusterRole. Optional.
     */
    additionalRoleBindings?: {
      clusterRoleName: string;
      /**
       * kubebuilder:validation:Minimum=1
       */
      subjects: {
        /**
         * APIGroup holds the API group of the referenced subject. Defaults to "" for ServiceAccount subjects. Defaults to "rbac.authorization.k8s.io" for User and Group subjects.
         */
        apiGroup?: string;
        /**
         * Kind of object being referenced. Values defined by this API group are "User", "Group", and "ServiceAccount". If the Authorizer does not recognized the kind value, the Authorizer should report an error.
         */
        kind: string;
        /**
         * Name of the object being referenced.
         */
        name: string;
        /**
         * Namespace of the referenced object.  If the object kind is non-namespace, such as "User" or "Group", and this value is not empty the Authorizer should report an error.
         */
        namespace?: string;
        [k: string]: any;
      }[];
      [k: string]: any;
    }[];
    /**
     * Specifies the trusted Image Registries assigned to the Tenant. Capsule assures that all Pods resources created in the Tenant can use only one of the allowed trusted registries. Optional.
     */
    containerRegistries?: {
      allowed?: string[];
      allowedRegex?: string;
      [k: string]: any;
    };
    /**
     * Specify the allowed values for the imagePullPolicies option in Pod resources. Capsule assures that all Pod resources created in the Tenant can use only one of the allowed policy. Optional.
     */
    imagePullPolicies?: ('Always' | 'Never' | 'IfNotPresent')[];
    /**
     * Specifies options for the Ingress resources, such as allowed hostnames and IngressClass. Optional.
     */
    ingressOptions?: {
      /**
       * Specifies the allowed IngressClasses assigned to the Tenant. Capsule assures that all Ingress resources created in the Tenant can use only one of the allowed IngressClasses. Optional.
       */
      allowedClasses?: {
        allowed?: string[];
        allowedRegex?: string;
        [k: string]: any;
      };
      /**
       * Specifies the allowed hostnames in Ingresses for the given Tenant. Capsule assures that all Ingress resources created in the Tenant can use only one of the allowed hostnames. Optional.
       */
      allowedHostnames?: {
        allowed?: string[];
        allowedRegex?: string;
        [k: string]: any;
      };
      /**
       * Defines the scope of hostname collision check performed when Tenant Owners create Ingress with allowed hostnames.
       *  - Cluster: disallow the creation of an Ingress if the pair hostname and path is already used across the Namespaces managed by Capsule.
       *  - Tenant: disallow the creation of an Ingress if the pair hostname and path is already used across the Namespaces of the Tenant.
       *  - Namespace: disallow the creation of an Ingress if the pair hostname and path is already used in the Ingress Namespace.
       *  Optional.
       */
      hostnameCollisionScope?: 'Cluster' | 'Tenant' | 'Namespace' | 'Disabled';
      [k: string]: any;
    };
    /**
     * Specifies the resource min/max usage restrictions to the Tenant. The assigned values are inherited by any namespace created in the Tenant. Optional.
     */
    limitRanges?: {
      items?: {
        /**
         * Limits is the list of LimitRangeItem objects that are enforced.
         */
        limits: {
          /**
           * Default resource requirement limit value by resource name if resource limit is omitted.
           */
          default?: {
            [k: string]: number | string;
          };
          /**
           * DefaultRequest is the default resource requirement request value by resource name if resource request is omitted.
           */
          defaultRequest?: {
            [k: string]: number | string;
          };
          /**
           * Max usage constraints on this kind by resource name.
           */
          max?: {
            [k: string]: number | string;
          };
          /**
           * MaxLimitRequestRatio if specified, the named resource must have a request and limit that are both non-zero where limit divided by request is less than or equal to the enumerated value; this represents the max burst for the named resource.
           */
          maxLimitRequestRatio?: {
            [k: string]: number | string;
          };
          /**
           * Min usage constraints on this kind by resource name.
           */
          min?: {
            [k: string]: number | string;
          };
          /**
           * Type of resource that this limit applies to.
           */
          type: string;
          [k: string]: any;
        }[];
        [k: string]: any;
      }[];
      [k: string]: any;
    };
    /**
     * Specifies options for the Namespaces, such as additional metadata or maximum number of namespaces allowed for that Tenant. Once the namespace quota assigned to the Tenant has been reached, the Tenant owner cannot create further namespaces. Optional.
     */
    namespaceOptions?: {
      /**
       * Specifies additional labels and annotations the Capsule operator places on any Namespace resource in the Tenant. Optional.
       */
      additionalMetadata?: {
        annotations?: {
          [k: string]: string;
        };
        labels?: {
          [k: string]: string;
        };
        [k: string]: any;
      };
      /**
       * Specifies the maximum number of namespaces allowed for that Tenant. Once the namespace quota assigned to the Tenant has been reached, the Tenant owner cannot create further namespaces. Optional.
       */
      quota?: number;
      [k: string]: any;
    };
    /**
     * Specifies the NetworkPolicies assigned to the Tenant. The assigned NetworkPolicies are inherited by any namespace created in the Tenant. Optional.
     */
    networkPolicies?: {
      items?: {
        /**
         * List of egress rules to be applied to the selected pods. Outgoing traffic is allowed if there are no NetworkPolicies selecting the pod (and cluster policy otherwise allows the traffic), OR if the traffic matches at least one egress rule across all of the NetworkPolicy objects whose podSelector matches the pod. If this field is empty then this NetworkPolicy limits all outgoing traffic (and serves solely to ensure that the pods it selects are isolated by default). This field is beta-level in 1.8
         */
        egress?: {
          /**
           * List of destination ports for outgoing traffic. Each item in this list is combined using a logical OR. If this field is empty or missing, this rule matches all ports (traffic not restricted by port). If this field is present and contains at least one item, then this rule allows traffic only if the traffic matches at least one port in the list.
           */
          ports?: {
            /**
             * If set, indicates that the range of ports from port to endPort, inclusive, should be allowed by the policy. This field cannot be defined if the port field is not defined or if the port field is defined as a named (string) port. The endPort must be equal or greater than port. This feature is in Beta state and is enabled by default. It can be disabled using the Feature Gate "NetworkPolicyEndPort".
             */
            endPort?: number;
            /**
             * The port on the given protocol. This can either be a numerical or named port on a pod. If this field is not provided, this matches all port names and numbers. If present, only traffic on the specified protocol AND port will be matched.
             */
            port?: number | string;
            /**
             * The protocol (TCP, UDP, or SCTP) which traffic must match. If not specified, this field defaults to TCP.
             */
            protocol?: string;
            [k: string]: any;
          }[];
          /**
           * List of destinations for outgoing traffic of pods selected for this rule. Items in this list are combined using a logical OR operation. If this field is empty or missing, this rule matches all destinations (traffic not restricted by destination). If this field is present and contains at least one item, this rule allows traffic only if the traffic matches at least one item in the to list.
           */
          to?: {
            /**
             * IPBlock defines policy on a particular IPBlock. If this field is set then neither of the other fields can be.
             */
            ipBlock?: {
              /**
               * CIDR is a string representing the IP Block Valid examples are "192.168.1.1/24" or "2001:db9::/64"
               */
              cidr: string;
              /**
               * Except is a slice of CIDRs that should not be included within an IP Block Valid examples are "192.168.1.1/24" or "2001:db9::/64" Except values will be rejected if they are outside the CIDR range
               */
              except?: string[];
              [k: string]: any;
            };
            /**
             * Selects Namespaces using cluster-scoped labels. This field follows standard label selector semantics; if present but empty, it selects all namespaces.
             *  If PodSelector is also set, then the NetworkPolicyPeer as a whole selects the Pods matching PodSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects all Pods in the Namespaces selected by NamespaceSelector.
             */
            namespaceSelector?: {
              /**
               * matchExpressions is a list of label selector requirements. The requirements are ANDed.
               */
              matchExpressions?: {
                /**
                 * key is the label key that the selector applies to.
                 */
                key: string;
                /**
                 * operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
                 */
                operator: string;
                /**
                 * values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
                 */
                values?: string[];
                [k: string]: any;
              }[];
              /**
               * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
               */
              matchLabels?: {
                [k: string]: string;
              };
              [k: string]: any;
            };
            /**
             * This is a label selector which selects Pods. This field follows standard label selector semantics; if present but empty, it selects all pods.
             *  If NamespaceSelector is also set, then the NetworkPolicyPeer as a whole selects the Pods matching PodSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects the Pods matching PodSelector in the policy's own Namespace.
             */
            podSelector?: {
              /**
               * matchExpressions is a list of label selector requirements. The requirements are ANDed.
               */
              matchExpressions?: {
                /**
                 * key is the label key that the selector applies to.
                 */
                key: string;
                /**
                 * operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
                 */
                operator: string;
                /**
                 * values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
                 */
                values?: string[];
                [k: string]: any;
              }[];
              /**
               * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
               */
              matchLabels?: {
                [k: string]: string;
              };
              [k: string]: any;
            };
            [k: string]: any;
          }[];
          [k: string]: any;
        }[];
        /**
         * List of ingress rules to be applied to the selected pods. Traffic is allowed to a pod if there are no NetworkPolicies selecting the pod (and cluster policy otherwise allows the traffic), OR if the traffic source is the pod's local node, OR if the traffic matches at least one ingress rule across all of the NetworkPolicy objects whose podSelector matches the pod. If this field is empty then this NetworkPolicy does not allow any traffic (and serves solely to ensure that the pods it selects are isolated by default)
         */
        ingress?: {
          /**
           * List of sources which should be able to access the pods selected for this rule. Items in this list are combined using a logical OR operation. If this field is empty or missing, this rule matches all sources (traffic not restricted by source). If this field is present and contains at least one item, this rule allows traffic only if the traffic matches at least one item in the from list.
           */
          from?: {
            /**
             * IPBlock defines policy on a particular IPBlock. If this field is set then neither of the other fields can be.
             */
            ipBlock?: {
              /**
               * CIDR is a string representing the IP Block Valid examples are "192.168.1.1/24" or "2001:db9::/64"
               */
              cidr: string;
              /**
               * Except is a slice of CIDRs that should not be included within an IP Block Valid examples are "192.168.1.1/24" or "2001:db9::/64" Except values will be rejected if they are outside the CIDR range
               */
              except?: string[];
              [k: string]: any;
            };
            /**
             * Selects Namespaces using cluster-scoped labels. This field follows standard label selector semantics; if present but empty, it selects all namespaces.
             *  If PodSelector is also set, then the NetworkPolicyPeer as a whole selects the Pods matching PodSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects all Pods in the Namespaces selected by NamespaceSelector.
             */
            namespaceSelector?: {
              /**
               * matchExpressions is a list of label selector requirements. The requirements are ANDed.
               */
              matchExpressions?: {
                /**
                 * key is the label key that the selector applies to.
                 */
                key: string;
                /**
                 * operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
                 */
                operator: string;
                /**
                 * values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
                 */
                values?: string[];
                [k: string]: any;
              }[];
              /**
               * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
               */
              matchLabels?: {
                [k: string]: string;
              };
              [k: string]: any;
            };
            /**
             * This is a label selector which selects Pods. This field follows standard label selector semantics; if present but empty, it selects all pods.
             *  If NamespaceSelector is also set, then the NetworkPolicyPeer as a whole selects the Pods matching PodSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects the Pods matching PodSelector in the policy's own Namespace.
             */
            podSelector?: {
              /**
               * matchExpressions is a list of label selector requirements. The requirements are ANDed.
               */
              matchExpressions?: {
                /**
                 * key is the label key that the selector applies to.
                 */
                key: string;
                /**
                 * operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
                 */
                operator: string;
                /**
                 * values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
                 */
                values?: string[];
                [k: string]: any;
              }[];
              /**
               * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
               */
              matchLabels?: {
                [k: string]: string;
              };
              [k: string]: any;
            };
            [k: string]: any;
          }[];
          /**
           * List of ports which should be made accessible on the pods selected for this rule. Each item in this list is combined using a logical OR. If this field is empty or missing, this rule matches all ports (traffic not restricted by port). If this field is present and contains at least one item, then this rule allows traffic only if the traffic matches at least one port in the list.
           */
          ports?: {
            /**
             * If set, indicates that the range of ports from port to endPort, inclusive, should be allowed by the policy. This field cannot be defined if the port field is not defined or if the port field is defined as a named (string) port. The endPort must be equal or greater than port. This feature is in Beta state and is enabled by default. It can be disabled using the Feature Gate "NetworkPolicyEndPort".
             */
            endPort?: number;
            /**
             * The port on the given protocol. This can either be a numerical or named port on a pod. If this field is not provided, this matches all port names and numbers. If present, only traffic on the specified protocol AND port will be matched.
             */
            port?: number | string;
            /**
             * The protocol (TCP, UDP, or SCTP) which traffic must match. If not specified, this field defaults to TCP.
             */
            protocol?: string;
            [k: string]: any;
          }[];
          [k: string]: any;
        }[];
        /**
         * Selects the pods to which this NetworkPolicy object applies. The array of ingress rules is applied to any pods selected by this field. Multiple network policies can select the same set of pods. In this case, the ingress rules for each are combined additively. This field is NOT optional and follows standard label selector semantics. An empty podSelector matches all pods in this namespace.
         */
        podSelector: {
          /**
           * matchExpressions is a list of label selector requirements. The requirements are ANDed.
           */
          matchExpressions?: {
            /**
             * key is the label key that the selector applies to.
             */
            key: string;
            /**
             * operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
             */
            operator: string;
            /**
             * values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
             */
            values?: string[];
            [k: string]: any;
          }[];
          /**
           * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
           */
          matchLabels?: {
            [k: string]: string;
          };
          [k: string]: any;
        };
        /**
         * List of rule types that the NetworkPolicy relates to. Valid options are ["Ingress"], ["Egress"], or ["Ingress", "Egress"]. If this field is not specified, it will default based on the existence of Ingress or Egress rules; policies that contain an Egress section are assumed to affect Egress, and all policies (whether or not they contain an Ingress section) are assumed to affect Ingress. If you want to write an egress-only policy, you must explicitly specify policyTypes [ "Egress" ]. Likewise, if you want to write a policy that specifies that no egress is allowed, you must specify a policyTypes value that include "Egress" (since such a policy would not include an Egress section and would otherwise default to just [ "Ingress" ]). This field is beta-level in 1.8
         */
        policyTypes?: string[];
        [k: string]: any;
      }[];
      [k: string]: any;
    };
    /**
     * Specifies the label to control the placement of pods on a given pool of worker nodes. All namespaces created within the Tenant will have the node selector annotation. This annotation tells the Kubernetes scheduler to place pods on the nodes having the selector label. Optional.
     */
    nodeSelector?: {
      [k: string]: string;
    };
    /**
     * Specifies the owners of the Tenant. Mandatory.
     */
    owners: {
      /**
       * Kind of tenant owner. Possible values are "User", "Group", and "ServiceAccount"
       */
      kind: 'User' | 'Group' | 'ServiceAccount';
      /**
       * Name of tenant owner.
       */
      name: string;
      /**
       * Proxy settings for tenant owner.
       */
      proxySettings?: {
        kind: 'Nodes' | 'StorageClasses' | 'IngressClasses' | 'PriorityClasses';
        operations: ('List' | 'Update' | 'Delete')[];
        [k: string]: any;
      }[];
      [k: string]: any;
    }[];
    /**
     * Specifies the allowed priorityClasses assigned to the Tenant. Capsule assures that all Pods resources created in the Tenant can use only one of the allowed PriorityClasses. Optional.
     */
    priorityClasses?: {
      allowed?: string[];
      allowedRegex?: string;
      [k: string]: any;
    };
    /**
     * Specifies a list of ResourceQuota resources assigned to the Tenant. The assigned values are inherited by any namespace created in the Tenant. The Capsule operator aggregates ResourceQuota at Tenant level, so that the hard quota is never crossed for the given Tenant. This permits the Tenant owner to consume resources in the Tenant regardless of the namespace. Optional.
     */
    resourceQuotas?: {
      items?: {
        /**
         * hard is the set of desired hard limits for each named resource. More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/
         */
        hard?: {
          [k: string]: number | string;
        };
        /**
         * scopeSelector is also a collection of filters like scopes that must match each object tracked by a quota but expressed using ScopeSelectorOperator in combination with possible values. For a resource to match, both scopes AND scopeSelector (if specified in spec), must be matched.
         */
        scopeSelector?: {
          /**
           * A list of scope selector requirements by scope of the resources.
           */
          matchExpressions?: {
            /**
             * Represents a scope's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist.
             */
            operator: string;
            /**
             * The name of the scope that the selector applies to.
             */
            scopeName: string;
            /**
             * An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
             */
            values?: string[];
            [k: string]: any;
          }[];
          [k: string]: any;
        };
        /**
         * A collection of filters that must match each object tracked by a quota. If not specified, the quota matches all objects.
         */
        scopes?: string[];
        [k: string]: any;
      }[];
      /**
       * Define if the Resource Budget should compute resource across all Namespaces in the Tenant or individually per cluster. Default is Tenant
       */
      scope?: 'Tenant' | 'Namespace';
      [k: string]: any;
    };
    /**
     * Duration for reconciliation loop to poll and ensure AdditionalResources are in correct state.
     */
    resyncPeriod?: string;
    /**
     * Specifies options for the Service, such as additional metadata or block of certain type of Services. Optional.
     */
    serviceOptions?: {
      /**
       * Specifies additional labels and annotations the Capsule operator places on any Service resource in the Tenant. Optional.
       */
      additionalMetadata?: {
        annotations?: {
          [k: string]: string;
        };
        labels?: {
          [k: string]: string;
        };
        [k: string]: any;
      };
      /**
       * Block or deny certain type of Services. Optional.
       */
      allowedServices?: {
        /**
         * Specifies if ExternalName service type resources are allowed for the Tenant. Default is true. Optional.
         */
        externalName?: boolean;
        /**
         * Specifies if LoadBalancer service type resources are allowed for the Tenant. Default is true. Optional.
         */
        loadBalancer?: boolean;
        /**
         * Specifies if NodePort service type resources are allowed for the Tenant. Default is true. Optional.
         */
        nodePort?: boolean;
        [k: string]: any;
      };
      /**
       * Specifies the external IPs that can be used in Services with type ClusterIP. An empty list means no IPs are allowed. Optional.
       */
      externalIPs?: {
        allowed: string[];
        [k: string]: any;
      };
      [k: string]: any;
    };
    /**
     * Specifies the allowed StorageClasses assigned to the Tenant. Capsule assures that all PersistentVolumeClaim resources created in the Tenant can use only one of the allowed StorageClasses. Optional.
     */
    storageClasses?: {
      allowed?: string[];
      allowedRegex?: string;
      [k: string]: any;
    };
    [k: string]: any;
  };
  /**
   * Returns the observed state of the Tenant.
   */
  status?: {
    /**
     * List of namespaces assigned to the Tenant.
     */
    namespaces?: string[];
    /**
     * How many namespaces are assigned to the Tenant.
     */
    size: number;
    /**
     * The operational state of the Tenant. Possible values are "Active", "Cordoned".
     */
    state: 'Cordoned' | 'Active';
    [k: string]: any;
  };
  [k: string]: any;
}
