/**
 * 由 src/kubernetes/gen/index.ts 自动生成
 * !!! 请不要修改 !!!
 */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Userview {
  spec?: {
    cluster?: string;
    kind?: string;
    namespace?: string;
    rolebinding?: string[];
    roles?: string[];
    user?: string;
    [k: string]: any;
  };
  status?: {
    holderIdentity?: string;
    owners?: {
      [k: string]: any;
    }[];
    renewTime?: string;
    [k: string]: any;
  };
  [k: string]: any;
}
